from datetime import date
fed = "federal_taxes"
ss_employer = "social_security_employer"
medicare_employer = "medicare_employer"
futa ="futa"
ss_employee = "social_security_employee"
medicare_employee = "medicare_employee"
ytd_ss_employer = "ytd_ss_employer"
ytd_medicare_employer = "ytd_medicare_employer"
ytd_futa = "ytd_futa"
ytd_ss_employee = "ytd_ss_employee"
ytd_medicare_employee = "ytd_medicare_employee"
gross = "gross"
net = "net"
cal = "california_taxes"
disability = "disability"
unemployment = "unemployment"
training = "training"
ytd_unemployment = "ytd_unemployment"
ytd_training = "ytd_training"
ytd_disability = "ytd_disability"
employee_collection="employees"
payroll_db = "PayRoll"
fn = "name_first"
ln = "name_last"
hours_per_sick = 30
year = "year"
end_q1 = date.fromisoformat("2021-03-31")
end_q2 = date.fromisoformat("2021-07-31")
end_q3 = date.fromisoformat("2021-09-30")
end_q4 = date.fromisoformat("2021-12-31")

